In [1]:
library(Seurat)
library(dplyr)
library(SingleR)
library(pheatmap)
library(ggplot2)
library(shiny)
library(ggalluvial)
library(ggpubr)
#library(metap)

Attaching SeuratObject


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘matrixStats’


The following object is masked from ‘package:dplyr’:

    count



Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:dplyr’:

    first, rename


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice


Loading required package: GenomeInfoDb

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians



Attaching package: ‘SummarizedExperiment’


The following object is masked from ‘package:SeuratObject’:

    Assays


The following object is masked from ‘package:Seurat’:

    Assays

In [2]:
zfsp=readRDS("/data/users/niuzhiwei1/online/00物种数据/11斑马鱼空间芯片/04周涛处理/05adata.region.0107_基因大写_同源转换.rds")

In [21]:
head(zfsp@meta.data)

               orig.ident nCount_RNA nFeature_RNA area x     y
39943195865150 sample     1380.725   401          NA    9300 12350
40587440959900 sample     1304.438   413          NA    9450 12700
43379169698050 sample     2341.699   937          NA   10100  8450
43593918063400 sample     1417.614   466          NA   10150  9000
43808666427800 sample     1845.221   729          NA   10200  8600
38869454040300 sample     2429.943   948          NA    9050 11500
               region                               nCounts_RNA slices batch ⋯
39943195865150 granular layer                       2733        NA     NA    ⋯
40587440959900 granular layer                       3383        NA     NA    ⋯
43379169698050 central zone of dorsal telencephalon 8430        NA     NA    ⋯
43593918063400 central zone of dorsal telencephalon 3783        NA     NA    ⋯
43808666427800 central zone of dorsal telencephalon 6470        NA     NA    ⋯
38869454040300 longitudinal torus                   7633        NA     NA    ⋯
               cluster level1 level0 level.1 species   leiden slice_code
39943195865150 NA      NA     NA     NA      zfish_spa 5      D03558D2.left
40587440959900 NA      NA     NA     NA      zfish_spa 5      D03558D2.left
43379169698050 NA      NA     NA     NA      zfish_spa 1      D03558D2.left
43593918063400 NA      NA     NA     NA      zfish_spa 27     D03558D2.left
43808666427800 NA      NA     NA     NA      zfish_spa 1      D03558D2.left
38869454040300 NA      NA     NA     NA      zfish_spa 19     D03558D2.left
               RNA_snn_res.0.1 seurat_clusters majorRegion
39943195865150 4               4               Cb
40587440959900 0               0               Cb
43379169698050 4               4               Tel
43593918063400 0               0               Tel
43808666427800 4               4               Tel
38869454040300 4               4               Mid

In [3]:
table(zfsp$slice_code)

 D03558D2.left D03558D2.right  D03558D4.left D03558D4.right
          7935           7752           7855           8425

In [5]:
Idents(zfsp)="region"

In [17]:
options(repr.plot.width=7, repr.plot.height=10)
p=DimPlot(subset(zfsp,subset=slice_code=="D03558D2.left"),reduction = "spatial",label = T)
pdf("zebrafish.D03558D2.left.bin.region.pdf",width = 11,height = 9)
p
dev.off()

png
  2

In [18]:
options(repr.plot.width=13, repr.plot.height=10)
p=DimPlot(subset(zfsp,subset=slice_code=="D03558D2.right"),reduction = "spatial",label = T)
pdf("zebrafish.D03558D2.right.bin.region.pdf",width = 11,height = 9)
p
dev.off()

png
  2

In [19]:
options(repr.plot.width=13, repr.plot.height=10)
p=DimPlot(subset(zfsp,subset=slice_code=="D03558D4.left"),reduction = "spatial",label = T)
pdf("zebrafish.D03558D4.left.bin.region.pdf",width = 11,height = 9)
p
dev.off()

png
  2

In [20]:
options(repr.plot.width=13, repr.plot.height=9)
p=DimPlot(subset(zfsp,subset=slice_code=="D03558D4.right"),reduction = "spatial",label = T)
pdf("zebrafish.D03558D4.right.bin.region.pdf",width = 11,height = 9)
p
dev.off()

png
  2

In [22]:
cball=readRDS("01斑马鱼空间_七鳃鳗空间_基因交集_cb_分析.rds")

In [40]:
tail(cball@meta.data)

               orig.ident nCount_RNA nFeature_RNA area x    y
30709016178950 sample      89        43           NA   7150 12550
31997506369200 sample     112        53           NA   7450 14000
31997506367750 sample     153        71           NA   7450 12550
31997506369150 sample     127        49           NA   7450 13950
28776280896400 sample      70        34           NA   6700 13200
28991029261800 sample      74        33           NA   6750 13800
               region          nCounts_RNA slices batch ⋯ level0 level.1
30709016178950 molecular layer 406         NA     NA    ⋯ NA     NA
31997506369200 molecular layer 393         NA     NA    ⋯ NA     NA
31997506367750 molecular layer 577         NA     NA    ⋯ NA     NA
31997506369150 molecular layer 401         NA     NA    ⋯ NA     NA
28776280896400 molecular layer 334         NA     NA    ⋯ NA     NA
28991029261800 molecular layer 279         NA     NA    ⋯ NA     NA
               species   same_names leiden slice_code    RNA_snn_res.0.1
30709016178950 zfish_spa Cb         6      D03558D4.left 0
31997506369200 zfish_spa Cb         23     D03558D4.left 0
31997506367750 zfish_spa Cb         5      D03558D4.left 0
31997506369150 zfish_spa Cb         23     D03558D4.left 0
28776280896400 zfish_spa Cb         6      D03558D4.left 0
28991029261800 zfish_spa Cb         5      D03558D4.left 0
               seurat_clusters majorRegion RNA_snn_res.0.5
30709016178950 0               Cb          0
31997506369200 0               Cb          0
31997506367750 4               Cb          4
31997506369150 0               Cb          0
28776280896400 0               Cb          0
28991029261800 8               Cb          8

In [41]:
table(cball@meta.data$region)

caudal lobe of cerebellum           cerebellum_area            granular layer
                      269                      3151                      1460
          molecular layer         nucleus_cerebelli
                     1738                       739

In [26]:
pdf("zf.les.cb.all.umap.pdf",width = 5,height = 5)
DimPlot(cball,label = T)+NoLegend()
dev.off()

png
  2

In [43]:
Idents(cball)="region"

In [27]:
pdf("zf.les.cb.split.umap.pdf",width = 10,height = 5)
DimPlot(cball,label = T,split.by = "species")+NoLegend()
dev.off()

png
  2

In [45]:
pdf("zf.les.cb.split.region.label.umap.pdf",width = 12,height = 5)
DimPlot(cball,split.by = "species")
dev.off()

png
  2

In [30]:
c1=rownames(cball@meta.data[which(cball@meta.data$species=="zfish_spa" & cball@meta.data$seurat_clusters %in% c(0,1,8)),])

In [35]:
p=DimPlot(subset(zfsp,subset=slice_code=="D03558D2.left"),reduction = "spatial",cells.highlight = c1)
pdf("zebrafish.D03558D2.left.bin.c018.pdf",width = 6,height = 9)
p
dev.off()

png
  2

In [36]:
p=DimPlot(subset(zfsp,subset=slice_code=="D03558D2.right"),reduction = "spatial",cells.highlight = c1)
pdf("zebrafish.D03558D2.right.bin.c018.pdf",width = 6,height = 9)
p
dev.off()

png
  2

In [37]:
p=DimPlot(subset(zfsp,subset=slice_code=="D03558D4.left"),reduction = "spatial",cells.highlight = c1)
pdf("zebrafish.D03558D4.left.bin.c018.pdf",width = 6,height = 9)
p
dev.off()

png
  2

In [38]:
p=DimPlot(subset(zfsp,subset=slice_code=="D03558D4.right"),reduction = "spatial",cells.highlight = c1)
pdf("zebrafish.D03558D4.right.bin.c018.pdf",width = 6,height = 9)
p
dev.off()

png
  2